version: '3.9'

services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_CREATE_TOPICS: "HelloWorldMicroservice:1:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

  helloworldmicroservice:
    build:
      context: .
      dockerfile: HelloWorldMicroservice/Dockerfile
    environment:
      - ServiceConfig__MessagingImplementation=Kafka
      - ServiceConfig__StartupDelayInterval=30000
      - KafkaConfig__Servers=kafka:9092
      - KafkaConfig__Topic=HelloWorldMicroservice
      - Logging__LogLevel__HelloWorldMicroservice=Information
    deploy:
      replicas: 3
    depends_on:
      - zookeeper
      - kafka
